language: generic

env:
  # We set the default value in global and changed it in the matrix when necessary
  global:
    - ENV=conda
    - ENV_NAME=test_env
    - MINIMAL_ENV=false
    - DEPS_OPTIONAL="scikit-learn"
    - TEST_DEPS="pytest pytest-cov pytest-mpl"
    - MPLBACKEND="agg"
    - PYTEST_MPL_ARGS="--mpl"

services:
  - xvfb

matrix:
  include:
    # All tests run for the latest supported Python version in Linux
  - env: export CONDA_PYTHON=3.7
  - env: export CONDA_PYTHON=3.7; MINIMAL_ENV=true
  - env: export ENV=pip
    language: python
    python: 3.7
  - env: export ENV=pip; MINIMAL_ENV=true
    language: python
    python: 3.7
    # Only standard test for older supported versions of Python in Linux
  - env: export CONDA_PYTHON=3.6
    # All tests, but the min requirements test run for the latest supported Python version in OSx
  - env: export CONDA_PYTHON=3.7
    os: osx
  - env: export CONDA_PYTHON=3.6
    os: osx
    if: tag IS present

before_install:
  # Clone the ci repo to get the ci setup scripts and execute the script
  - git clone --depth 1 git://github.com/ericpre/ci.git
  - source ci/travis/setup_travis.sh

install:
  # Install the package
  - pip install git+https://github.com/hyperspy/hyperspy.git

script:
  - which python
  - python -c 'import matplotlib.pyplot as plt; print("Matplotlib backend:", plt.get_backend())';
  # We don't run image comparison when installing from pip because of the freetype version mismatch
  - if [ $ENV == pip ]; then PYTEST_MPL_ARGS=""; fi
  - pytest --pyargs hyperspy --cov=hyperspy $PYTEST_MPL_ARGS;

after_success:
- coveralls
- python setup.py bdist_wheel sdist;

before_deploy:
- export DISTRIB=$(ls ./dist/*);

deploy:
  provider: releases
  api_key:
    # ericpre, secure key define in the travis account settings
    secure: ${GITHUB_TOKEN_ERICPRE}
  file: "${DISTRIB}"
  skip_cleanup: true
  on:
    tags: true
    condition: $MINIMAL_ENV = false
