jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda init
    displayName: Add conda to PATH

  - bash: |
      conda create --yes --quiet --name test_env python=$PYTHON_VERSION
      conda env --name test_env update --file conda_environment.yml
    displayName: Setup Anaconda packages

  - bash: |
      conda activate test_env
      pip install https://github.com/hyperspy/hyperspy.git
      pytest --mpl --pyargs hyperspy
    displayName: pytest
