variables:
  TEST_DEPS: pytest pytest-cov pytest-mpl pytest-azurepipelines

jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python36:
        python.version: '3.6'

  steps:
  - bash: |
      git clone --depth 1 git://github.com/ericpre/ci.git
    displayName: Clone CI repository

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      source ci/conda_setup_environment.sh

    displayName: Setup Anaconda packages

  - bash: |
      source activate test_env
      # Install package using pip
      pip install git+https://github.com/hyperspy/hyperspy.git
      conda list
    displayName: Install package

  - bash: |
      source activate test_env
      conda list
      python -c 'import matplotlib.pyplot as plt; print(plt.get_backend())'
      python -c 'import hyperspy.api as hs; print(hs.print_known_signal_types())'
      python -c 'import hyperspy; print(hyperspy.__version__)'
      python -c 'import hyperspy; print(hyperspy.__file__)'
      pytest --mpl --pyargs hyperspy
    displayName: pytest

- job:
  displayName: vs2017-win2016
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python36:
        python.version: '3.6'

  steps:
  - bash: |
      git clone --depth 1 git://github.com/ericpre/ci.git
    displayName: Clone CI repository

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - bash: |
      conda config --append channels conda-forge
      conda create --yes --quiet --name test_env python=$PYTHON_VERSION
      conda env update --name test_env --file conda_environment.yml
      source activate test_env
      conda install -y $DEPS $TEST_DEPS
      conda info
      conda list
      # source ci/conda_setup_environment.sh
    displayName: Setup Anaconda packages

  - script: |
      call activate test_env
      # Install package using pip
      pip install git+https://github.com/hyperspy/hyperspy.git
      conda list
    displayName: Install package

  - script: |
      call activate test_env
      python -c 'import matplotlib.pyplot as plt; print(plt.get_backend())'
      python -c 'import hyperspy.api as hs; print(hs.print_known_signal_types())'
      python -c 'import hyperspy; print(hyperspy.__version__)'
      python -c 'import hyperspy; print(hyperspy.__file__)'
      pytest --mpl --pyargs hyperspy
    displayName: pytest

- job:
  displayName: macOS-10.13
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - bash: |
      git clone --depth 1 git://github.com/ericpre/ci.git
    displayName: Clone CI repository

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  # On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
  # We need to take ownership if we want to update conda or install packages globally
  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: |
      conda config --append channels conda-forge
      conda create --yes --quiet --name test_env python=$PYTHON_VERSION
      conda env update --name test_env --file conda_environment.yml
      source activate test_env
      conda install -y $DEPS $TEST_DEPS
      conda info
      conda list
    displayName: Setup Anaconda packages

  - bash: |
      source activate test_env
      # Install package using pip
      pip install git+https://github.com/hyperspy/hyperspy.git
      conda list
    displayName: Install package

  - bash: |
      source activate test_env
      python -c 'import matplotlib.pyplot as plt; print(plt.get_backend())'
      python -c 'import hyperspy.api as hs; print(hs.print_known_signal_types())'
      python -c 'import hyperspy; print(hyperspy.__version__)'
      python -c 'import hyperspy; print(hyperspy.__file__)'
      pytest --mpl --pyargs hyperspy
    displayName: pytest
