variables:
  TEST_DEPS: pytest pytest-cov pytest-mpl

jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python36:
        python.version: '3.6'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      source conda_setup_environment.sh

    displayName: Setup Anaconda packages

  - bash: |
      source activate test_env
      # Install package using pip
      pip install git+https://github.com/hyperspy/hyperspy.git
    displayName: Install package

  - bash: |
      source activate test_env
      pytest --mpl --pyargs hyperspy
    displayName: pytest
