name: test_env
channels:
- defaults
- conda-forge
dependencies:
# Minimal dependencies
- numpy
- scipy
- matplotlib
- traits
- natsort
- requests
- tqdm
- sympy
- dill
- h5py
- python-dateutil
- ipyparallel
- dask
- scikit-image
- pint
- statsmodels
- numexpr
- sparse
- imageio
- pyyaml
- PTable

